import {test} from 'node:test';import assert from 'node:assert/strict';
// In-memory IndexedDB stand-in, exercising real AES-GCM and vault lifecycle.
const records=new Map();
const fakeDB={createObjectStore(){},transaction(){const tx={objectStore(){return{get(k){return run(()=>records.get(k))},put(v,k){return run(()=>{records.set(k,structuredClone(v));return k})},clear(){return run(()=>records.clear())}}}};function run(fn){const req={};setTimeout(()=>{try{req.result=fn();req.onsuccess?.();setTimeout(()=>tx.oncomplete?.(),0)}catch(e){tx.error=e;tx.onerror?.()}},0);return req}return tx}};
globalThis.indexedDB={open(){const req={};setTimeout(()=>{req.result=fakeDB;req.onupgradeneeded?.();req.onsuccess?.()},0);return req}};
const {saveVault,loadVault,clearVault}=await import('../dist/vault.mjs');
test('vault stores ciphertext with non-extractable AES key and restores exact data',async()=>{await clearVault();const data={schema:1,cases:[{text:'Synthetic investment example'}]};await saveVault(data);assert.deepEqual(await loadVault(),data);assert.equal(records.get('key').extractable,false);assert(records.get('data').body instanceof ArrayBuffer);assert(!new TextDecoder().decode(records.get('data').body).includes('Synthetic investment example'))});
test('clear removes encrypted data and its key',async()=>{await clearVault();assert.equal(records.size,0);assert.equal(await loadVault(),null)});
test('an encryption operation pending at deletion cannot resurrect deleted cases',async()=>{await saveVault({schema:1,cases:[]});const original=crypto.subtle.encrypt.bind(crypto.subtle);let entered,release;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);crypto.subtle.encrypt=async(...args)=>{entered();await gate;return original(...args)};try{const pending=saveVault({schema:1,cases:[{text:'Pending synthetic case'}]});await started;await clearVault();release();await pending;assert.equal(records.size,0);assert.equal(await loadVault(),null)}finally{crypto.subtle.encrypt=original}});
test('rapid successive saves retain the latest revision',async()=>{await clearVault();await Promise.all([saveVault({revision:1}),saveVault({revision:2})]);assert.deepEqual(await loadVault(),{revision:2})});
